# Server settings
server.port=${SONG_SERVICE_PORT:8082}

# Database settings
spring.datasource.url=jdbc:postgresql://${SONG_DB_HOST:localhost}:${SONG_DB_PORT:5433}/${SONG_DB_NAME:song_service_db}
spring.datasource.username=${SONG_DB_USERNAME:postgres}
spring.datasource.password=${SONG_DB_PASSWORD:postgres}
spring.jpa.hibernate.ddl-auto=none
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.properties.hibernate.format_sql=true

# Set the log level
logging.level.org.springframework=INFO
logging.level.com.epam.microservices=INFO
logging.level.org.hibernate.SQL=DEBUG
