# Server settings
spring.application.name=eureka-service
server.port=${EUREKA_SERVER_PORT:8761}

# Eureka settings
eureka.client.register-with-eureka=false
eureka.client.fetch-registry=false
eureka.server.wait-time-in-ms-when-sync-empty=0

# Logging
logging.level.org.springframework=INFO
logging.level.com.epam.microservices=INFO
